---
# Update and upgrade the system packages
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

# Check for a file that indicates a reboot is required
- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

# Reboot if the flagged file exists (kernel update, etc.)
- name: Reboot if required
  reboot:
    msg: "Rebooting due to a kernel update"
  when: reboot_required_file.stat.exists

# Install the list of common packages (from group_vars/all/vars.yml)
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present

# Install Python pip packages
- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

# Free port 53 by setting DNS values in systemd-resolved config
- name: Free port 53
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#DNS="
    line: "DNS=1.1.1.1"

- name: Free port 53 Part 2
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#DNSStubListener=yes"
    line: "DNSStubListener=no"

# Create symbolic link for systemd-resolved
- name: Create symbolic link for resolv.conf
  shell: sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

# Reboot the server to apply DNS changes and free up port 53
- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Rebooting server to free port"